name: khalti_checkout_core
description: An official wrapper around Khalti Payment Gateway's REST API.
version: 1.0.0-dev.5
homepage: https://khalti.com/payment-gateway/
documentation: https://docs.khalti.com/
issue_tracker: https://github.com/khalti/checkout-sdk-flutter/issues
repository: https://github.com/khalti/checkout-sdk-flutter/tree/main/packages/khalti_checkout_core

environment:
  sdk: ^3.4.0

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.2.2
  package_info_plus: ^8.2.0
  equatable: ^2.0.7
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  package_info_plus_platform_interface: ^3.1.0
  plugin_platform_interface: ^2.1.8
  test: ^1.25.14
