name: khalti_checkout_flutter
description: An official Flutter plugin for Khalti Payment Gateway, with all the necessary interface that make it easy to integrate with your app.
version: 1.0.0-dev.3
homepage: https://khalti.com/payment-gateway/
documentation: https://docs.khalti.com/
issue_tracker: https://github.com/khalti/checkout-sdk-flutter/issues
repository: https://github.com/khalti/checkout-sdk-flutter/tree/main/packages/khalti_checkout_flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

platforms:
  android:
  ios:

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  http: ^1.2.0
  internet_connection_checker_plus: ^2.2.0
  khalti_checkout_core: ^1.0.0-dev.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  test: ^1.25.2
